version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
        - .env
    volumes:
      - ../:/workspaces:cached
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:12-bookworm
    restart: unless-stopped
    volumes:
      - ../appdata/psql-data:/var/lib/postgresql/data
      - ../:/home/workspace
    env_file:
        - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
        - .env
    volumes:
      - ../appdata/pga-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres