version: '3.8'

services:
  postgres:
    image: postgres:12-bookworm
    restart: unless-stopped
    volumes:
      - ../appdata/psql-data:/tmp/dev/pgsql/data
      - ../:/home/workspace
    env_file:
        - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
        - .env
    volumes:
      - ../appdata/pga-data:/tmp/dev/pga/data
    ports:
      - "5050:80"
    depends_on:
      - postgres